### PR TITLE
Confirming Docker Functionality and Full Build Upload

### PR DESCRIPTION
**Pull request by gwaygenomics**

### CODE REVIEW

**Comment by jaclyn-taroni** [comment]
Remove "Build docker image" step
Change the command to clone the repository to include the appropriate URL
For the run step, add some language that instructs the reader to replace the "PATH/TO/GIT" in the path

I was able to download the full build and extract files without issue.

**Comment by gwaygenomics** [comment]
I removed the build step and added the right URL. I removed the "PATH/TO/GIT" all together since the instructions are to clone the repo and then run the docker image directly after. Thanks!

**Comment by gwaygenomics** [comment]
Ok, I think I made it more clear about where to mount the host volume. Does it make sense?

**Comment by jaclyn-taroni** [comment]
Yes, looks good to me.

**Pull request merged**
